### ISSUE TITLE
Test issue.  Let's see how this feels.

### ISSUE THREAD

**Issue by judeallred** [FogCreek/Glitch-Community#67]
Steps:
  1. open github
  2. go to glitch-community
  3. type 'gi'
  4. click 'new issue'

expected:
  easily file an issue

actual:
  let's find out....

**Comment by judeallred** [comment]
what happens if I ping @GregWeil and ask what he thinks?

**Comment by judeallred** [comment]
My thoughts are: 
  1. notion.so has some strengths, but filing tickets is not one of them-- there are a lot of steps,  and it doesn't integrate well with other tools.  It should be very easy to file a bug report.
  2. we're in PR's anyway, putting our bug reports in github shouldn't add much overhead.
  3. there are still more steps than I would like in filing a case via github, however all of the other tools we use are very likely to integrate with github;   can I file an issue via slack, for example?  probably.  
  4. ~community is open source, so having our bugs be open should be OK.
  5. _features_ are different.  We should keep our specs and stuff in other spots.

**Comment by judeallred** [comment]
attaching some chat context:

> <https://sentry.io/fog-creek-software/community/issues/613797036/> looks like the error report
<sub>[View in Slack](https://fogcreek.slack.com/archives/CB4EHAJ2J/p1532459646000100)</sub>

**Comment by GregWeil** [comment]
i wonder if we could treat sentry as the issue tracker. most common errors will get a report there with info we'll be referencing when we actually fix the bug. idk how to handle bugs that don't end up there though

**Comment by GregWeil** [comment]
i guess known issues that don't make it to sentry should manually send an error so we can get the data around what led to it anyways

**Comment by judeallred** [comment]
we could use https://sentry.io/fog-creek-software/community/user-feedback/ to submit issues

**Comment by judeallred** [comment]
good to know the options here, but adding yet another thing doesn't make sense right now as we're not positioned to remove anything.
