### ISSUE TITLE
Active file is wiped off when editor is idle (when switching back to the tab after a long time of inactivity).

### ISSUE THREAD

**Issue by chroventer** [FogCreek/Glitch-Community#682]
The Glitch editor disconnects, once the tab is idle for a long time - currently, ignoring that. But, when I switch back to the editor's tab, Glitch auto-reloads the editor and the active file is blank, which I was working on. To get it back, I need to make sure I don’t type anything. Instead, I have to click to another file and then click back on the file that was blank. Thenceforth, it properly loads the file and the content inside the file. This has been happening for quite a while for me. I’m using Chrome 75, and haven’t tested in other browsers.

[Check out the other Glitch editor bugs](https://support.glitch.com/t/glitch-editor-caret-moves-to-the-right-side-of-a-character-even-if-you-click-to-the-left-of-the-center-of-that-character/5163)

Source: [Glitch Support](https://support.glitch.com/t/active-file-is-wiped-when-editor-reloads-when-switching-back-to-the-tab-after-a-long-time-of-inactivity/12084?u=chroventer)

Reported by: [joe](https://support.glitch.com/u/joe)

**Comment by cori** [comment]
Hey @chroventer thanks for the issue! Unfortunately this bug is with a different part of the Glitch codebase unrelated to the Community site, but we have a case open in our internal system to track it.
