### ISSUE TITLE
Folders Don't Collapse

### ISSUE THREAD

**Issue by ZebTheWizard** [FogCreek/Glitch-Community#693]
Folders don't collapse. Instead, they show the path of the file relative to the project root. If this is not a feature, it would be nice if it was. It would make sense to display it like that if there is only one thing in the folder, but once there is more than one, it becomes an eyesore. 

![image](https://user-images.githubusercontent.com/13527122/60384722-f0cf0c80-9a46-11e9-88d2-317ff85a31f5.png)

**Comment by jennschiffer** [comment]
hey zeb - thanks for the editor request! i'm going to pass it on to the dev tools team (who work on the editor) and close this issue (this repo is for the ~community site).
